general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.


  # Commands to run just before the WM is shutdown.
 
  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    enabled: true
    trigger: 'monitor_focus'

gaps:
  scale_with_dpi: true
  inner_gap: "3px"
  outer_gap:
    top: "12px"
    right: "12px"
    bottom: "12px"
    left: "12px"

window_effects:
  focused_window:
    border:
      enabled: true
      color: "#8c49ff"
      width: "20px"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: 'rounded'

  other_windows:
    border:
      enabled: true
      color: "#000000"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: true
      style: 'rounded'

window_behavior:
  initial_state: 'tiling'

  state_defaults:
    floating:
      centered: true
      shown_on_top: false
    fullscreen:
      maximized: false
      shown_on_top: false

workspaces:
  - name: '1'
  - name: '2'
  - name: '3'
  - name: '4'
  - name: '5'
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'

window_rules:
  - commands: ['ignore']
    match:
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }
      - window_process: { equals: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }
      - window_process: { equals: 'PowerToys' }
        window_title: { regex: '.*? - Peek' }
      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper' }

binding_modes:
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -4%']
        bindings: ['h', 'left']
      - commands: ['resize --width +4%']
        bindings: ['l', 'right']
      - commands: ['resize --height +5%']
        bindings: ['k', 'up']
      - commands: ['resize --height -5%']
        bindings: ['j', 'down']
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']

  - name: 'pause'
    keybindings:
      - commands: ['wm-disable-binding-mode --name pause']
        bindings: ['alt+shift+p']

keybindings:
  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["Alt+H"]
  - commands: ["focus --direction right"]
    bindings: ["Alt+L"]
  - commands: ["focus --direction up"]
    bindings: ["Alt+K", "Alt+Up"]
  - commands: ["focus --direction down"]
    bindings: ["Alt+J", "Alt+Down"]

  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["Alt+Shift+H", "Alt+Shift+Left"]
  - commands: ["move --direction right"]
    bindings: ["Alt+Shift+L", "Alt+Shift+Right"]
  - commands: ["move --direction up"]
    bindings: ["Alt+Shift+K", "Alt+Shift+Up"]
  - commands: ["move --direction down"]
    bindings: ["Alt+Shift+J", "Alt+Shift+Down"]

  # Resize focused window by a percentage or pixel amount.
  - commands: ["resize --width -5%"]
    bindings: ["Alt+U"]
  - commands: ["resize --width +5%"]
    bindings: ["Alt+P"]
  - commands: ["resize --height +5%"]
    bindings: ["Alt+O"]
  - commands: ["resize --height -5%"]
    bindings: ["Alt+I"]


  # Enable resize mode
  # - commands: ['wm-enable-binding-mode --name resize']
  #   bindings: ['alt+r']

  # Enable pause mode (to pause WM bindings)
  - commands: ['wm-enable-binding-mode --name pause']
    bindings: ['alt+shift+p']

  # Toggle tiling direction between vertical and horizontal
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']

  # Cycle focus between windows
  - commands: ['wm-cycle-focus']
    bindings: ['alt+space']

  # Toggle floating mode and center the window
  - commands: ['toggle-floating --centered']
    bindings: ['alt+shift+space']

  # Toggle tiling mode
  - commands: ['toggle-tiling']
    bindings: ['alt+t']

  # Toggle fullscreen mode
  - commands: ['toggle-fullscreen']
    bindings: ['alt+f']

  # Minimize the window
  - commands: ['toggle-minimized']
    bindings: ['alt+m']

  # Close the focused window
  - commands: ['close']
    bindings: ['alt+shift+q']

  # Exit the window manager
  - commands: ['wm-exit']
    bindings: ['alt+shift+e']

  # Reload the configuration file
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+r']

  # Redraw the WM interface
  - commands: ['wm-redraw']
    bindings: ['alt+shift+w']

  # Open the default terminal (shell execution command)
  - commands: ['shell-exec wt']
    bindings: ['alt+enter']




  # Workspace navigation
  - commands: ['focus --next-workspace']
    bindings: ['alt+s']
  - commands: ['focus --prev-workspace']
    bindings: ['alt+a']
  - commands: ['focus --recent-workspace']
    bindings: ['alt+d']
  - commands: ['focus --workspace 1']
    bindings: ['alt+1']
  - commands: ['focus --workspace 2']
    bindings: ['alt+2']
  - commands: ['focus --workspace 3']
    bindings: ['alt+3']
  - commands: ['focus --workspace 4']
    bindings: ['alt+4']
  - commands: ['focus --workspace 5']
    bindings: ['alt+5']
  - commands: ['focus --workspace 6']
    bindings: ['alt+6']
  - commands: ['focus --workspace 7']
    bindings: ['alt+7']
  - commands: ['focus --workspace 8']
    bindings: ['alt+8']
  - commands: ['focus --workspace 9']
    bindings: ['alt+9']

  # Move window to a different workspace
  - commands: ['move-workspace --direction left']
    bindings: ['alt+shift+a']
  - commands: ['move-workspace --direction right']
    bindings: ['alt+shift+f']
  - commands: ['move-workspace --direction up']
    bindings: ['alt+shift+d']
  - commands: ['move-workspace --direction down']
    bindings: ['alt+shift+s']
  - commands: ['move --workspace 1']
    bindings: ['alt+shift+1']
  - commands: ['move --workspace 2']
    bindings: ['alt+shift+2']
  - commands: ['move --workspace 3']
    bindings: ['alt+shift+3']
  - commands: ['move --workspace 4']
    bindings: ['alt+shift+4']
  - commands: ['move --workspace 5']
    bindings: ['alt+shift+5']
  - commands: ['move --workspace 6']
    bindings: ['alt+shift+6']
  - commands: ['move --workspace 7']
    bindings: ['alt+shift+7']
  - commands: ['move --workspace 8']
    bindings: ['alt+shift+8']
  - commands: ['move --workspace 9']
    bindings: ['alt+shift+9']

  # Close the focused window with a fallback option for Alt+F4
  - commands: ['close']
    bindings: ['alt+q']
    options:
      keys: ['alt+f4']

  # Toggle fullscreen mode with Alt+Shift+F
  - commands: ['toggle-fullscreen']
    bindings: ['alt+shift+f']
